model:
  base_learning_rate: 1e-2
  target: ldm.models.scd.networks.SemiSCDNet
  params: 
    monitor: "val/F_scd"
    in_channels: 3
    num_classes: 7
    mid_dim: 128
    unsup_final_w: 30
    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10]
        cycle_lengths: [20000]
        f_start: [1.e-6]
        f_max: [0.1]
        f_min: [1.e-5]
    confidence_masking: False
    confidence_th: 0.5
    rc_config:
      unsup_final_w: 30
      confidence_masking: False
      confidence_th: 0.5
      drop: 5
      drop_rate: 0.5
      spatial: True
      cutout: 5
      erase: 0.4
      vat: 2
      xi: 1.e-6
      eps: 2.0
      context_masking: 2
      object_masking: 2
      feature_drop: 5
      feature_noise: 5
      uniform_range: 0.3
    
data:
  target: ldm.data.SCDDatasetFromConfig
  params:
    num_workers: 4
    wrap: false
    sup_train_size: 8
    unsup_train_size: 8
    val_size: 8
    test_size: 1
    train_supervised:
      target: ldm.data.SCDDataloader.ImageDataset
      params: 
        data_dir: "/data/datasets/SECOND_scd/"
        crop_size: 512
        scale: True
        augment: True
        flip: True
        rotate: True
        blur: True
        split: "train_supervised"
        percnt_lbl: 10
        data_len: 20
    train_unsupervised:
      target: ldm.data.SCDDataloader.ImageDataset
      params:
        data_dir: "/data/datasets/SECOND_scd/"
        crop_size: 512
        base_size: 512
        scale: True
        augment: True
        flip: True
        rotate: True
        blur: True
        split: "train_unsupervised"
        percnt_lbl: 10
        data_len: 40
    validation:
      target: ldm.data.SCDDataloader.ImageDataset
      params: 
        data_dir: "/data/datasets/SECOND_scd/"
        split: "val"
        data_len: 10
    test:
      target: ldm.data.SCDDataloader.ImageDataset
      params: 
        data_dir: "/data/datasets/SECOND_scd/"
        split: "test"
        data_len: 10

lightning:
  trainer:
      benchmark: True
      accumulate_grad_batches: 1
      gpus: [0]
      max_epochs: 3
      log_every_n_steps: 20
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        clamp: False
        batch_frequency: 100
        max_images: 4
        increase_log_steps: True
