
lightning:
  trainer:
      benchmark: True
      accumulate_grad_batches: 1
      gpus: [1]
      max_epochs: 40
      log_every_n_steps: 50
      precision: 16
  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params: 
      mode: max
      auto_insert_metric_name: False
      filename: "{epoch:03}-{val/F_scd:.4f}"
  
