
lightning:
  trainer:
      benchmark: True
      accumulate_grad_batches: 1
      gpus: [1]
      max_epochs: 100
      log_every_n_steps: 50
  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params: 
      mode: max
      filename: "{epoch:03}-{val/F_scd:.4f}"
  
