
lightning:
  trainer:
      benchmark: True
      accumulate_grad_batches: 1
      gpus: [0]
      max_epochs: 100
      log_every_n_steps: 50
  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params: 
      mode: "max"
      auto_insert_metric_name: True
      filename: "{epoch:03}-Fscd={val\\F_scd:.4f}"
