model:
  base_learning_rate: 2.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusionSCD
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: ['image_A','image_B']
    image_size: 32
    channels: 128
    monitor: val/loss

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 128
        out_channels: 128
        model_channels: 128
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.scd.networks.SCDNet
      params:
        in_channels: 3
        num_classes: 7
        mid_dim: 128
        # ckpt_path: models/first_stage_models/vq-f4/model.ckpt
    cond_stage_config: __is_unconditional__