model:
  base_learning_rate: 1e-2
  target: src.models.scd.networks.SemiMTSCD
  params: 
    use_ema: True
    monitor: "val/F_scd"
    in_channels: 3
    num_classes: 7
    mid_dim: 128
    unsup_final_w: 30
    scheduler_config: # 10000 warmup steps
      target: src.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [100]
        cycle_lengths: [20000]
        f_start: [1.e-4]
        f_max: [1]
        f_min: [1.e-3]
    confidence_masking: False
    confidence_th: 0.5
    rc_config:
      unsup_final_w: 30
      confidence_masking: False
      confidence_th: 0.5
      drop: 5
      drop_rate: 0.5
      spatial: True
      cutout: 5
      erase: 0.4
      vat: 2
      xi: 1.e-6
      eps: 2.0
      context_masking: 2
      object_masking: 2
      feature_drop: 5
      feature_noise: 5
      uniform_range: 0.3
    