model:
  base_learning_rate: 2.0e-06
  target: src.models.diffusion.ddpm_scd.LatentDiffusionSCD
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: ['image_A','image_B']
    image_size: 16
    channels: 128
    monitor: val/loss

    unet_config:
      target: src.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 16
        in_channels: 1024 
        out_channels: 1024
        model_channels: 128
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_head_channels: 32
    first_stage_config:
      target: src.models.scd.networks.SCDNet
      params:
        in_channels: 3
        num_classes: 7
        mid_dim: 128
        # ckpt_path: models/first_stage_models/vq-f4/model.ckpt
    cond_stage_config: __is_unconditional__

   
data:
  target: src.data.SCDDatasetFromConfig
  params:
    num_workers: 4
    wrap: false
    sup_train_size: 8
    unsup_train_size: 8
    val_size: 8
    test_size: 1
    train_supervised:
      target: src.data.SCDDataloader.ImageDataset
      params: 
        data_dir: "/data/datasets/SECOND_scd/"
        crop_size: 512
        scale: True
        augment: True
        flip: True
        rotate: True
        blur: True
        split: "train_supervised"
        percnt_lbl: 10
        data_len: -1
    validation:
      target: src.data.SCDDataloader.ImageDataset
      params: 
        data_dir: "/data/datasets/SECOND_scd/"
        split: "val"
        data_len: -1
    test:
      target: src.data.SCDDataloader.ImageDataset
      params: 
        data_dir: "/data/datasets/SECOND_scd/"
        split: "test"
        data_len: -1

lightning:
  trainer:
    benchmark: True
    accumulate_grad_batches: 1
    gpus: [0]
    max_epochs: 100
    log_every_n_steps: 50
  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params: 
      mode: min

    
  
